### ISSUE TITLE
Pebble Round

### ISSUE THREAD

**Issue by garsim** [andrei-markeev/pebble-onenote#1]
Hi, is there any chance to enable compatibility for this app with pebble round?

**Comment by andrei-markeev** [comment]
Hi, just went to CloudPebble and read this news: "Pebble.js can now build Chalk apps for Pebble Time Round. You can enable this in the settings of your pebble.js project." -- which means probably yes, since the app is implemented using Pebble.js! I will try this out today.

**Comment by garsim** [comment]
Ok, good! I will wait this implementation and then i will try the app on my Round :)

**Comment by andrei-markeev** [comment]
Alright, I just tried it with the emulator. Navigating notebooks -> sections -> pages works fine, but the text of the note itself is cut on the edges, as if the screen is square.

It will take some time to understand if I can do something about that - Pebble.js framework was significantly updated and at least it now includes features for determining if the watch is Round, so I can implement Round-specific logic for placing the text correctly.

**Comment by garsim** [comment]
i've no experience with developing in pebble ecosystem, however with a fast reading of the documentation i found this https://developer.pebble.com/guides/design-and-interaction/in-the-round/

**Comment by andrei-markeev** [comment]
Ok, I added a simplified support for Pebble Round (i.e. for example lists will be displayed without numbering or bullet points). There might be crashes, especially when trying to view long notes. Short simple notes should work fine.

You can find the new version in the app store (search "OneNote").

**Comment by garsim** [comment]
I can confirm, it works with simple notes

**Comment by andrei-markeev** [comment]
Great, thanks :) Closing this.

P. S. I'll be trying to improve the Round experience in future, but because of non-trivial text reflow it might require quite some time to make it work.
