### ISSUE TITLE
App Issues

### ISSUE THREAD

**Issue by sxcd** [andrei-markeev/pebble-onenote#2]
Past few days the app has been acting a bit erratic, the view for the Notebooks area and the Sections is fine, but the Pages area seems to have been messed up now, and it's a bit unpredictable. The pages in a Section seems to be showing anything such as:

- pages in another section
- deleted pages from other section
- "Pages not found"
- old pages from the same section

I've tried using a different account without any success. Sometimes the pages in that Section would be right but I get the Graph ApI error code for no pages. I'm not sure what the reason could be, maybe an update in the API? It would be really helpful if you could look into this, as I'm an avid user of this app

Thank you

**Comment by andrei-markeev** [comment]
Hello, thanks for reporting!

Yep, I wouldn't be surprised if there was even some API update, even though Microsoft is usually providing great backwards compatibility, but MSGraph is sometimes quirky and sometimes certain endpoints are unstable.

I will check as soon as I can.

**Comment by sxcd** [comment]
Extremely sorry for the ping and I know these take time, but just curious if it has been looked into?

**Comment by andrei-markeev** [comment]
Hey, sorry, not yet. Two of my kids are having birthdays during these 7 days so it was quite hectic 😄

**Comment by andrei-markeev** [comment]
Ok, I started looking into it, but the tooling that is necessary to debug the app (`cloudpebble-composed`) no longer compiles. Will continue tomorrow.

**Comment by andrei-markeev** [comment]
For now, still no luck compiling cloudpebble, unfortunately. I was able to struggle through 3 different errors, but then there's a always a new one. Haven't found any "ready-made" solutions in internet or Pebble discord, so have to continue trying 😬

**Comment by sxcd** [comment]
Thanks for the effort, isn't cloudpebble dysfunctional for a while now? Are you trying to self host via docker? I think the only bulletproof alternative I've read is getting the entire SDK(https://github.com/andyburris/pebble-setup)  but I'm not really sure or aware if there exists a better way

**Comment by andrei-markeev** [comment]
I was running it locally last time when I did changes to the pebble-onenote, which was couple years ago.

Actually, I did get it working tonight finally 🎉. Everything seems to work except the emulator... At least I can build the package now.

**Comment by andrei-markeev** [comment]
Sorry for the delay again with this, basically didn't have time to investigate further yet. Maybe this weekend :)

**Comment by sxcd** [comment]
Have you been able to look through it?😅

**Comment by andrei-markeev** [comment]
Hello, just a note that the app works again in 2024 😊 
Just updated it to version 1.11.
At least I don't seem to have any issues currently.
